nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  weverse:
    npmAlwaysAuth: true
    npmAuthIdent: '${BENX_NPM_AUTH_TOKEN}'
    npmPublishRegistry: 'https://nexus.relengd.benxdevops.io/repository/npm-private/'
    npmRegistryServer: 'https://nexus.relengd.benxdevops.io/repository/npm-group/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
